1. Creating Tensors (1D, 2D, 3D)

In [ ]:
import torch
import numpy as np

# --- 1D (Vector) ---
np_1d = np.array([1, 2, 3])
pt_1d = torch.tensor([1, 2, 3])

# --- 2D (Matrix) ---
np_2d = np.array([[1, 2, 3], [4, 5, 6]])
pt_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

# --- 3D (Batch of Matrices) ---
# Shape: (2, 2, 3) -> 2 matrices, each 2x3
np_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
pt_3d = torch.tensor([[[1, 2, 3], [4, 5, 6]],
                      [[7, 8, 9], [10, 11, 12]]])

print(f"PyTorch 3D Shape: {pt_3d.shape}")
print(f"NumPy 3D Shape: {np_3d.shape}")

PyTorch 3D Shape: torch.Size([2, 2, 3])
NumPy 3D Shape: (2, 2, 3)


2. Basic Operations

In [ ]:
x = torch.tensor([10, 20, 30])
y = torch.tensor([1, 2, 3])

# Addition
print(x + y)        # tensor([11, 22, 33])
print(torch.add(x, y))

# Subtraction
print(x - y)        # tensor([ 9, 18, 27])

# Multiplication (Element-wise)
print(x * y)        # tensor([10, 40, 90])

# Division
print(x / y)        # tensor([10., 10., 10.])

tensor([11, 22, 33])
tensor([11, 22, 33])
tensor([ 9, 18, 27])
tensor([10, 40, 90])
tensor([10., 10., 10.])


3. Dot Product and Matrix Multiplication

In [ ]:
# --- Dot Product (1D) ---
v1 = torch.tensor([1, 2])
v2 = torch.tensor([3, 4])

# PyTorch
dot_pt = torch.dot(v1, v2)  # 1*3 + 2*4 = 11

# NumPy
dot_np = np.dot(v1.numpy(), v2.numpy()) # 11


# --- Matrix Multiplication (2D) ---
mat_a = torch.tensor([[1, 2], [3, 4]]) # 2x2
mat_b = torch.tensor([[1, 0], [0, 1]]) # 2x2 Identity

# Method 1: The @ operator (Works in both NumPy and PyTorch)
res_at = mat_a @ mat_b

# Method 2: Library specific functions
res_pt = torch.matmul(mat_a, mat_b)
res_np = np.matmul(mat_a.numpy(), mat_b.numpy())

4. Indexing and Slicing

In [ ]:
data = torch.tensor([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

# 1. Extracting Subtensors
# Get first 2 rows, and column index 1 (middle column)
sub_slice = data[:2, 1]
print(sub_slice) # tensor([20, 50])

# 2. Boolean Masking
# Select all elements greater than 50
mask = data > 50
filtered = data[mask]
print(filtered) # tensor([60, 70, 80, 90])

tensor([20, 50])
tensor([60, 70, 80, 90])


5. Shape Manipulation


.view() --> "Reshapes tensor but requires data to be contiguous in memory. Fast and memory efficient (returns a view, not a copy)."

.reshape() --> "Reshapes tensor. In PyTorch, it handles non-contiguous data by copying it if necessary. Safer but potentially slower than .view()."

.unsqueeze() --> Adds a dimension of size 1 at a specific index.

.squeeze() --> Removes all dimensions of size 1.

In [ ]:
t = torch.arange(12) # [0, 1, ..., 11]

# --- View vs Reshape ---
view_t = t.view(3, 4)      # Reshape to 3 rows, 4 cols
resh_t = t.reshape(3, 4)   # Same result

# --- Squeeze / Unsqueeze ---
# Current shape: (3, 4)
unsq_t = view_t.unsqueeze(0)
# New shape: (1, 3, 4) -> Added 'batch' dimension at index 0

sq_t = unsq_t.squeeze()
# New shape: (3, 4) -> Removed the dimension with size 1

6. Broadcasting

In [ ]:
# A is (2, 3)
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# B is (1, 3) - effectively a row vector
B = torch.tensor([[10, 20, 30]])

# B is "broadcast" down to match A's 2 rows
result = A + B
# Row 1: [1,2,3] + [10,20,30]
# Row 2: [4,5,6] + [10,20,30]

print(result)
# tensor([[11, 22, 33],
#         [14, 25, 36]])

tensor([[11, 22, 33],
        [14, 25, 36]])


7. In-place vs Out-of-place

In [ ]:
x = torch.tensor([1, 2, 3])

# --- Out-of-place ---
y = x.add(5)
print(x) # tensor([1, 2, 3]) - x is unchanged
print(y) # tensor([6, 7, 8]) - y is a new tensor

# --- In-place (Note the underscore) ---
x.add_(5)
print(x) # tensor([6, 7, 8]) - x is now modified!

tensor([1, 2, 3])
tensor([6, 7, 8])
tensor([6, 7, 8])
